version: "3.8"

services:
  bootnode:
    image: hyperledger/besu:latest
    container_name: besu-bootnode
    volumes:
      - ./config/genesis.json:/config/genesis.json
      - ./config/bootnode/nodekey:/config/nodekey
    command: >
      --network-id=2025
      --data-path=/data
      --node-private-key-file=/config/nodekey
      --genesis-file=/config/genesis.json
      --bootnodes=
      --p2p-port=30301
      --rpc-http-enabled=false
      --rpc-ws-enabled=false
      --host-whitelist="*"
      --discovery-enabled=true
      --miner-enabled=false
    ports:
      - "30301:30301/udp"
      - "30301:30301/tcp"

  validator1:
    image: hyperledger/besu:latest
    container_name: besu-validator1
    depends_on:
      - bootnode
    volumes:
      - ./config/genesis.json:/config/genesis.json
      - ./config/validator1/nodekey:/config/nodekey
    command: >
      --network-id=2025
      --data-path=/data
      --node-private-key-file=/config/nodekey
      --genesis-file=/config/genesis.json
      --bootnodes=enode://SEU_ENODE_BOOTNODE@bootnode:30301
      --p2p-port=30302
      --rpc-http-enabled=true
      --rpc-http-port=8545
      --rpc-ws-enabled=true
      --rpc-ws-port=8546
      --host-whitelist="*"
      --discovery-enabled=true
      --miner-enabled=false
      --rpc-http-api=ETH,NET,IBFT,ADMIN,DEBUG,MINER,WEB3,TXPOOL
      --rpc-ws-api=ETH,NET,IBFT,ADMIN,DEBUG,MINER,WEB3,TXPOOL
      # Configurações IBFT
      --plugin-dir=/usr/lib/besu/plugins
    ports:
      - "30302:30302"
      - "8545:8545"
      - "8546:8546"

  validator2:
    image: hyperledger/besu:latest
    container_name: besu-validator2
    depends_on:
      - bootnode
    volumes:
      - ./config/genesis.json:/config/genesis.json
      - ./config/validator2/nodekey:/config/nodekey
    command: >
      --network-id=2025
      --data-path=/data
      --node-private-key-file=/config/nodekey
      --genesis-file=/config/genesis.json
      --bootnodes=enode://SEU_ENODE_BOOTNODE@bootnode:30301
      --p2p-port=30303
      --rpc-http-enabled=true
      --rpc-http-port=8547
      --rpc-ws-enabled=true
      --rpc-ws-port=8548
      --host-whitelist="*"
      --discovery-enabled=true
      --miner-enabled=false
      --rpc-http-api=ETH,NET,IBFT,ADMIN,DEBUG,MINER,WEB3,TXPOOL
      --rpc-ws-api=ETH,NET,IBFT,ADMIN,DEBUG,MINER,WEB3,TXPOOL
      --plugin-dir=/usr/lib/besu/plugins
    ports:
      - "30303:30303"
      - "8547:8547"
      - "8548:8548"

  client:
    image: hyperledger/besu:latest
    container_name: besu-client
    depends_on:
      - bootnode
    volumes:
      - ./config/genesis.json:/config/genesis.json
      - ./config/client/nodekey:/config/nodekey
    command: >
      --network-id=2025
      --data-path=/data
      --node-private-key-file=/config/nodekey
      --genesis-file=/config/genesis.json
      --bootnodes=enode://SEU_ENODE_BOOTNODE@bootnode:30301
      --p2p-port=30304
      --rpc-http-enabled=true
      --rpc-http-port=8550
      --rpc-ws-enabled=true
      --rpc-ws-port=8551
      --host-whitelist="*"
      --discovery-enabled=true
      --miner-enabled=false
      --rpc-http-api=ETH,NET,ADMIN,DEBUG,WEB3,TXPOOL
      --rpc-ws-api=ETH,NET,ADMIN,DEBUG,WEB3,TXPOOL
    ports:
      - "30304:30304"
      - "8550:8550"
      - "8551:8551"
